core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('instagram_clone.urls')),
    path('user/', include('users.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

instagram_clone/urls.py
from django.urls import path

from instagram_clone import views

app_name = "insta"

urlpatterns = [
    path('', views.home, name='home'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('profile/<int:id>/edit/', views.profile_edit, name='profile_edit'),
    path('post/like/', views.post_like, name='post_like'),
    path('post/<int:id>/edit', views.post_edit, name='post_edit'),
    path('post/new/', views.post_new, name='post_new'),
]

users/urls.py
from django.urls import path

from users import views

app_name = "users"

urlpatterns = [
    path('login/', views.login_page, name='login'),
    path('signup/', views.signup_page, name='signup'),
]

users/models.py
from django.db import models

# Create your models here.

users/forms/login_form.py
from django import forms


class LoginForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    username = forms.CharField(
        widget=forms.TextInput(attrs={
            'placeholder': 'Your username',
        })
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'placeholder': 'Your password',
        })
    )

users/views/all.py
from django.shortcuts import render


def login_page(request):
    return render(request, 'users/pages/login.html')


def signup_page(request):
    return render(request, 'users/pages/signup.html')

users/templates/users/pages/login.html
{% extends 'global/base.html' %}

{% load static %}

{% block style_css %}
{% include 'users/partials/style.html' %}
{% endblock style_css %}

{% block title %}Login | {% endblock title %}

{% block content %}

<div class="form-login">
    <h1>Instagram</h1>

    <form action="{% url 'insta:home' %}">
        <input type="email" name="email" placeholder="username or email">
        <input type="password" name="password" placeholder="Password">
        <button type="submit">Log in</button>
    </form>

    <div class="or">
        <div class="line"></div>
        <p>OR</p>
        <div class="line"></div>
    </div>
    
    <div class="other-options">
        <a href="">
            <i class="face fa-brands fa-square-facebook"></i>
            Log in with Facebook
        </a>

        <a href="" class="forgot-password">Forgot password ?</a>
    </div>
</div>

<div class="sign-up">
    <p>Don't have an account? <a href="{% url 'users:signup' %}">Sign up</a></p>
</div>

{% endblock content %}

users/templates/users/pages/signup.html
{% extends 'global/base.html' %}

{% load static %}

{% block style_css %}
{% include 'users/partials/style.html' %}
{% endblock style_css %}

{% block title %}Login | {% endblock title %}

{% block content %}

<div class="form-login">
    <h1>Instagram</h1>
                
    <div class="other-options">
        <a href="">
            <i class="face fa-brands fa-square-facebook"></i>
            Log in with Facebook
        </a>

        <a href="" class="forgot-password">Forgot password ?</a>
    </div>

    <div class="or">
        <div class="line"></div>
        <p>OR</p>
        <div class="line"></div>
    </div>

    <form action="">
        <input type="text" name="first-name" placeholder="First name">
        <input type="text" name="last-name" placeholder="Last name">
        <input type="email" name="email" placeholder="username or email">
        <input type="password" name="password" placeholder="Password">
        <p>People who use our service may have uploaded your contact information to Instagram. Learn More</p>
        <p>By signing up, you agree to our Terms , Privacy Policy and Cookies Policy .</p>
        <button type="submit">Sign up</button>
    </form>
</div>

<div class="sign-up">
    <p>Have an account? <a href="{% url 'users:login' %}">Log in</a></p>
</div>

{% endblock content %}