core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('instagram_clone.urls')),
    path('user/', include('users.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

instagram_clone/urls.py
from django.urls import path

from instagram_clone import views

app_name = "insta"

urlpatterns = [
    path('', views.home, name='home'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('profile/<int:id>/edit/', views.profile_edit, name='profile_edit'),
    path('post/like/', views.post_like, name='post_like'),
    path('post/<int:id>/edit', views.post_edit, name='post_edit'),
    path('post/new/', views.post_new, name='post_new'),
]

instagram_clone/models/comment_model.py
from django.contrib.auth.models import User
from django.db import models
from .post_model import Post


class Comment(models.Model):
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True
    )
    post = models.ForeignKey(
        Post, on_delete=models.SET_NULL, null=True
    )

    def __str__(self):
        return self.description

instagram_clone/models/like_model.py
from django.contrib.auth.models import User
from django.db import models

from .post_model import Post


class Like(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True
    )
    post = models.ForeignKey(
        Post, on_delete=models.SET_NULL, null=True
    )

instagram_clone/models/post_model.py
from django.contrib.auth.models import User
from django.db import models


class Post(models.Model):
    caption = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    photo = models.ImageField(
        upload_to='instagram_clone/post_photos/', blank=True, default='')
    user = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True
    )

    def __str__(self):
        return self.caption

instagram_clone/models/profile_model.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(default='', blank=True)
    phone = models.CharField(max_length=100)
    photo = models.ImageField(
        upload_to='instagram_clone/profile_photos/', blank=True, default='')
    gender = models.CharField(max_length=20)
    website = models.CharField(max_length=100)

instagram_clone/forms/post_form.py
from django import forms

from instagram_clone.models import Post


class PostForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    class Meta:
        model = Post
        fields = [
            'photo',
            'caption',
        ]

    caption = forms.Textarea()
    photo = forms.ImageField(
        widget=forms.FileInput(attrs={
            'onchange': 'preview()',
        }),
        label='Photo',
        error_messages={'required': 'This field must not be empty'},
    )

instagram_clone/forms/profile_form.py
from django import forms
from django.contrib.auth.models import User

from instagram_clone.models import Profile


class UserForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'username',
            'email',
        ]


class ProfileForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    class Meta:
        model = Profile
        fields = [
            'bio',
            'phone',
            'photo',
            'gender',
            'website',
        ]

    photo = forms.ImageField(
        widget=forms.FileInput(attrs={
            'onchange': 'preview()',
        }),
        label='Photo',
        error_messages={'required': 'This field must not be empty'},
    )

instagram_clone/views/all.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.shortcuts import redirect, render
from django.urls import reverse

from instagram_clone.forms import PostForm
from instagram_clone.models import Like, Post


@login_required(login_url='users:login', redirect_field_name='next')
def home(request):
    posts = Post.objects.all()
    dados: list[str] = []
    for post in posts:
        liked = Like.objects.filter(
            user=request.user,
            post=post,
        ).first()

        likes = Like.objects.filter(
            post=post,
        ).count()
        dados.append((
                post,
                {
                    'liked': liked,
                    'n_likes': likes,
                },
            ))

    return render(request, 'instagram_clone/pages/home.html', {
        'range': range(10),
        'posts': dados,
    })


@login_required(login_url='users:login', redirect_field_name='next')
def post_edit(request, id):
    post = Post.objects.filter(
        user=request.user,
        pk=id,
    ).first()

    if not post:
        raise Http404()

    form = PostForm(
        data=request.POST or None,
        files=request.FILES or None,
        instance=post,
    )

    if form.is_valid():
        post = form.save(commit=False)
        post.user = request.user
        post.save()

        messages.success(request, 'Save successfully!')
        return redirect(reverse('insta:post_edit', args=(id,)))

    return render(
        request,
        'instagram_clone/pages/post_form.html',
        context={
            'form': form,
            'form_action': reverse('insta:post_edit', args=(id,)),
        }
    )


@login_required(login_url='users:login', redirect_field_name='next')
def post_new(request):
    form = PostForm(
        data=request.POST or None,
        files=request.FILES or None,
    )

    if form.is_valid():
        post: Post = form.save(commit=False)

        post.user = request.user
        post.save()

        messages.success(request, 'Saved successfully')
        return redirect(reverse('insta:post_edit', args=(post.id,)))

    return render(
        request,
        'instagram_clone/pages/post_form.html',
        context={
            'form': form,
            'form_action': reverse('insta:post_new')
        }
    )


@login_required(login_url='users:login', redirect_field_name='next')
def post_like(request):
    if not request.POST:
        return redirect(reverse('insta:home'))

    if request.POST.get('username') != request.user.username:
        return redirect(reverse('insta:home'))

    like = Like.objects.filter(
        user=request.user,
        post=Post.objects.filter(id=request.POST.get('post')).first(),
    )

    if like:
        like.delete()
    else:
        like = Like(
            user=request.user,
            post=Post.objects.filter(id=request.POST.get('post')).first(),
        )
        like.clean()
        like.save()

    post_id = '#post'+request.POST.get('post')

    return redirect(reverse('insta:home')+post_id)

instagram_clone/views/home_view.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from instagram_clone.models import Like, Post


@login_required(login_url='users:login', redirect_field_name='next')
def home(request):
    posts = Post.objects.all().order_by('-id')
    dados: list[str] = []
    for post in posts:
        liked = Like.objects.filter(
            user=request.user,
            post=post,
        ).first()

        likes = Like.objects.filter(
            post=post,
        ).count()
        dados.append((
            post,
            {
                'liked': liked,
                'n_likes': likes,
            },
        ))

    return render(request, 'instagram_clone/pages/home.html', {
        'range': range(10),
        'posts': dados,
    })

instagram_clone/views/post_view.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.shortcuts import redirect, render
from django.urls import reverse

from instagram_clone.forms import PostForm
from instagram_clone.models import Like, Post


@login_required(login_url='users:login', redirect_field_name='next')
def post_edit(request, id):
    post = Post.objects.filter(
        user=request.user,
        pk=id,
    ).first()

    if not post:
        raise Http404()

    form = PostForm(
        data=request.POST or None,
        files=request.FILES or None,
        instance=post,
    )

    if form.is_valid():
        post = form.save(commit=False)
        post.user = request.user
        post.save()

        messages.success(request, 'Save successfully!')
        return redirect(reverse('insta:post_edit', args=(id,)))

    return render(
        request,
        'instagram_clone/pages/post_form.html',
        context={
            'form': form,
            'form_action': reverse('insta:post_edit', args=(id,)),
        }
    )


@login_required(login_url='users:login', redirect_field_name='next')
def post_new(request):
    form = PostForm(
        data=request.POST or None,
        files=request.FILES or None,
    )

    if form.is_valid():
        post: Post = form.save(commit=False)

        post.user = request.user
        post.save()

        messages.success(request, 'Saved successfully')
        return redirect(reverse('insta:post_edit', args=(post.id,)))

    return render(
        request,
        'instagram_clone/pages/post_form.html',
        context={
            'form': form,
            'form_action': reverse('insta:post_new')
        }
    )


@login_required(login_url='users:login', redirect_field_name='next')
def post_like(request):
    if not request.POST:
        return redirect(reverse('insta:home'))

    if request.POST.get('username') != request.user.username:
        return redirect(reverse('insta:home'))

    like = Like.objects.filter(
        user=request.user,
        post=Post.objects.filter(id=request.POST.get('post')).first(),
    )

    if like:
        like.delete()
    else:
        like = Like(
            user=request.user,
            post=Post.objects.filter(id=request.POST.get('post')).first(),
        )
        like.clean()
        like.save()

    post_id = '#post'+request.POST.get('post')

    return redirect(reverse('insta:home')+post_id)

instagram_clone/views/profile_view.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.shortcuts import redirect, render
from django.urls import reverse

from instagram_clone.forms import ProfileForm, UserForm
from instagram_clone.models import Like, Post, Profile


@login_required(login_url='users:login', redirect_field_name='next')
def profile(request, username):
    posts = Post.objects.filter(user__username=username)
    num_posts = posts.count()
    dados: list[str] = []
    for post in posts:
        num_likes = Like.objects.filter(
            post=post,
        ).count()
        dados.append((
            post,
            num_likes,
        ))

    profile = Profile.objects.filter(user__username=username).first()
    return render(request, 'instagram_clone/pages/profile.html', {
        'profile': profile,
        'posts': dados,
        'num_posts': num_posts,
    })


@login_required(login_url='users:login', redirect_field_name='next')
def profile_edit(request, id):
    profile = Profile.objects.filter(
        user=request.user,
    ).first()

    if request.user.id != id:
        raise Http404()

    user_form = UserForm(
        data=request.POST or None,
        instance=request.user,
    )
    profile_form = ProfileForm(
        data=request.POST or None,
        files=request.FILES or None,
        instance=profile,
    )

    if user_form.is_valid() & profile_form.is_valid():
        user = user_form.save(commit=False)
        user.save()

        profile = profile_form.save(commit=False)
        profile.save()

        messages.success(request, 'Save successfully!')
        return redirect(reverse('insta:profile_edit', args=(id,)))

    return render(
        request,
        'instagram_clone/pages/profile_edit.html',
        context={
            'user_form': user_form,
            'profile_form': profile_form,
            'form_action': reverse('insta:profile_edit', args=(id,)),
        }
    )

instagram_clone/templates/instagram_clone/pages/home.html
{% extends 'global/base.html' %}

{% load static %}

{% block style_css %}
<link rel="stylesheet" href="{% static 'global/css/style.css' %}">
{% endblock style_css %}

{% block title %}Home | {% endblock title %}

{% block header %}
{% include 'instagram_clone/partials/header.html' %}
{% endblock header %}

{% block content %}

{% include 'global/partials/messages.html' %}

<section class="stories-box">
    {% for n in range %}
        <article class="profile-storie">
            <div class="profile-img">
                <img src="{% static 'global/images/profile-example1.png' %}" alt="">
            </div>
            <p>user - {{ n }}</p>
        </article>
    {% endfor %}
</section>

<section class="feed-box">
    {% for post, like in posts %}
        <article class="post-box" id="post{{post.id}}">
            <header>
                <div class="profile-post">
                    <div class="shadow-img">
                        <img src="{% static 'global/images/profile-example1.png' %}" alt="">
                    </div>
                    <p><a href="{% url 'insta:profile' post.user %}" class="link-desnatado">{{post.user}}</a></p>
                </div>
                {% if request.user.id == post.user.id %}
                    <a href="{% url 'insta:post_edit' post.id %}" class="more">...</a>
                {% else %}
                    <a class="more">...</a>
                {% endif %}
            </header>

            <div class="post-photo">
                <img src="/media/{{post.photo}}" alt="">
            </div>

            <div class="reaction-post">
                <div class="reaction-direct">
                    <a>
                        <form class="inline-form form-logout" action="{% url 'insta:post_like' %}" method='POST'>
                            {% csrf_token %}
                            <input type="hidden" name="username" value="{{ request.user }}">
                            <input type="hidden" name="post" value="{{ post.id }}">
                            <button type="submit">
                                {% if like.liked %}
                                    <i class="fa-solid fa-heart" style="color: red;"></i>
                                {% else %}
                                    <i class="fa-regular fa-heart"></i>
                                {% endif %}
                            </button>
                        </form>
                    </a>
                    <a href="">
                        <i class="fa-regular fa-message"></i>
                    </a>
                    <a href="">
                        <i class="fa-regular fa-paper-plane"></i>
                    </a>
                </div>
                <div class="reaction-favorite">
                    <a href="">
                        <i class="fa-regular fa-bookmark"></i>
                    </a>
                </div>
            </div>

            <div class="post-content">
                <div class="likes">
                    {{like.n_likes}} likes
                </div>

                <div class="content">
                    <span><a href="{% url 'insta:profile' post.user %}" class="link-desnatado">{{post.user}}</a></span>
                    <p class="post-content-p">{{post.caption}}</p>
                </div>

                <div class="comments">
                    <a href="">View all 86 comments</a>
                </div>

                <div class="post-date">
                    {{post.created_at}}
                </div>
            </div>

            <div class="send-comment">
                <i class="fa-regular fa-face-smile"></i>

                <form action="" method="get">
                    <input type="text" placeholder="Add a comment...">
                    <button type="submit">Post</button>
                </form>
            </div>
        </article>
    {% endfor %}
</section>

{% endblock content  %}

instagram_clone/templates/instagram_clone/pages/post_form.html
{% extends 'global/base.html' %}

{% load static %}

{% block style_css %}
<link rel="stylesheet" href="{% static 'global/css/style.css' %}">
<link rel="stylesheet" href="{% static 'global/css/post_form.css' %}">
{% endblock style_css %}

{% block title %}Post | {% endblock title %}

{% block header %}
{% include 'instagram_clone/partials/header.html' %}
{% endblock header %}

{% block content %}

{% include 'global/partials/messages.html' %}

<div class="post-form">
    <form action="{{ form_action }}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        {% for field in form %}
            <div class="form-group">
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{field}}
                {% if field.label == 'Photo' %}
                    <img src="/media/{{field.value}}" alt="" id="photo">
                    <div class="btn-cancelar" id="cancelar" onclick="cancelar()" style="display: none;">Cancelar</div>
                {% endif %}
                {{field.errors}}
            </div>
        {% endfor %}
        <button type="submit">Post</button>
    </form>
</div>

<script>
    var img = document.getElementById('photo').src;
    document.body.style.setProperty('--bg', 'url('+img+')');
    localStorage.setItem('imagem', '');

    function cancelar() {
        document.getElementById('id_photo').value='';
        document.getElementById('photo').src=localStorage.getItem('imagem');
        document.getElementById('cancelar').style.display='none';
        document.body.style.setProperty('--bg', 'url('+localStorage.getItem('imagem')+')');
    }
    function preview() {
        let file = document.getElementById('id_photo');
        
        let photo = document.getElementById('photo');
        if(localStorage.getItem('imagem')=='') {
            localStorage.setItem('imagem', photo.src);
        }

        document.getElementById('cancelar').style.display='inline-block';

        let reader = new FileReader();

        reader.onload = () => {
            photo.src = reader.result;
            document.body.style.setProperty('--bg', 'url('+reader.result+')');
        }

        reader.readAsDataURL(file.files[0])
    }
</script>

{% endblock content  %}

instagram_clone/templates/instagram_clone/pages/profile.html
{% extends 'global/base.html' %}

{% load static %}

{% block style_css %}
<link rel="stylesheet" href="{% static 'global/css/style.css' %}">
<link rel="stylesheet" href="{% static 'global/css/profile.css' %}">
{% endblock style_css %}

{% block title %}Profile | {% endblock title %}

{% block header %}
{% include 'instagram_clone/partials/header.html' %}
{% endblock header %}

{% block content %}

{% include 'global/partials/messages.html' %}

<section class="profile-box">

    <div class="profile-top">
        <div class="photo-profile">
            <img src="/media/{{profile.photo}}">
        </div>

        <div class="info-profile">
            <div class="edit">
                <p>{{profile.user.username}}</p>
                {% if profile.user.id == request.user.id %}
                    <a href="{% url 'insta:profile_edit' profile.user.id %}">Edit profile</a>
                {% endif %}
            </div>

            <div>
                {{profile.bio}}
            </div>

            <div class="numbers">
                <div><span>{{num_posts}}</span> posts</div>
                <div><span>0</span> followers</div>
                <div><span>0</span> following</div>
            </div>

            <div class="name">
                {{profile.user.first_name}} {{profile.user.last_name}}
            </div>
        </div>
    </div>

    <div class="profile-down">
        <nav>
            <a href="" class="option-profile-selected">POSTS</a>
            <a href="">SAVED</a>
            <a href="">TAGGED</a>
        </nav>
    </div>

</section>

<section class="profile-posts">
    {% for post, num_likes in posts %}
        <article class="post-box">
            <figcaption>{{num_likes}} likes | 0 comments</figcaption>
            <img style="background: url(/media/{{ post.photo }});background-size: cover;background-position: 50% 50%;">
        </article>
    {% endfor %}
</section>

{% endblock content  %}

instagram_clone/templates/instagram_clone/pages/profile_edit.html
{% extends 'global/base.html' %}

{% load static %}

{% block style_css %}
<link rel="stylesheet" href="{% static 'global/css/style.css' %}">
<link rel="stylesheet" href="{% static 'global/css/menu.css' %}">
<link rel="stylesheet" href="{% static 'global/css/profile_edit.css' %}">
{% endblock style_css %}

{% block title %}Profile | {% endblock title %}

{% block header %}
{% include 'instagram_clone/partials/header.html' %}
{% endblock header %}

{% block content %}

{% include 'global/partials/messages.html' %}

<div class="menu-status-frame">
    {% include 'instagram_clone/partials/menu.html' %}
</div>

<section class="profile-edit-box">
    <nav class="menu-box">
        <a class="active">Edit profile</a>
        <a>Change password</a>
        <a>Apps and websites</a>
        <a>Email notifications</a>
        <a>Push notifications</a>
        <a>Manage contacts</a>
        <a>Privacy and security</a>
        <a>Ads</a>
        <a>Supervision</a>
        <a>Login activity</a>
        <a>Emails from Instagram</a>
        <a>Help</a>
        <a>Logout</a>
    </nav>

    <div class="profile-form">
        <form action="{{ form_action }}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
    
            {% for field in user_form %}
                <div class="form-group">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{field}}
                    {{field.errors}}
                </div>
            {% endfor %}

            {% for field in profile_form %}
                <div class="form-group">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{field}}
                    {% if field.label == 'Photo' %}
                        <img src="/media/{{field.value}}" alt="" id="photo">
                        <div class="btn-cancelar" id="cancelar" onclick="cancelar()" style="display: none;">Cancelar</div>
                    {% endif %}
                    {{field.errors}}
                </div>
            {% endfor %}
            <button type="submit">Update</button>
        </form>
    </div>
</section>
<script>
    var img = document.getElementById('photo').src;
    document.body.style.setProperty('--bg', 'url('+img+')');
    localStorage.setItem('imagem', '');

    function cancelar() {
        document.getElementById('id_photo').value='';
        document.getElementById('photo').src=localStorage.getItem('imagem');
        document.getElementById('cancelar').style.display='none';
        document.body.style.setProperty('--bg', 'url('+localStorage.getItem('imagem')+')');
    }
    function preview() {
        let file = document.getElementById('id_photo');
        
        let photo = document.getElementById('photo');
        if(localStorage.getItem('imagem')=='') {
            localStorage.setItem('imagem', photo.src);
        }

        document.getElementById('cancelar').style.display='inline-block';

        let reader = new FileReader();

        reader.onload = () => {
            photo.src = reader.result;
            document.body.style.setProperty('--bg', 'url('+reader.result+')');
        }

        reader.readAsDataURL(file.files[0])
    }
</script>

<script src="{% static 'global/js/scripts.js' %}"></script>
{% endblock content  %}